### ISSUE TITLE
Error occurred during creating affordance map

### ISSUE THREAD

**Issue by yangshuo11** [weiyx16/Active-Perception#3]
Hello, I am recently running your code in ubuntu16.04, ros kinetic, and v-rep 3.6.1. When I start the simulation of V-rep scene, and run the command "python main.py --is_train=True" to perform training, the following error occurs. It seems that the affordance map cannot be created in the former step of "os.system(affordance_cmd)". Would you please help me with this issue? Thanks a lot! The log is as follows:

(active-perception) ys@huang:~/Active-Perception/DQN$ python main.py --is_train=True
/home/ys/anaconda3/envs/active-perception/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
/home/ys/anaconda3/envs/active-perception/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
--- Successfully load vrep ---
 [*] Use GPU Fraction is : 0.6000
2019-09-25 20:43:31.029367: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA

 [*] Current Configuration
{'Lua_PATH': '../affordance_model/infer.lua',
 'batch_size': 16,
 'ckpt_dir': './dqn/checkpoint',
 'cnn_format': 'NHWC',
 'discount': 0.6,
 'end_metric': 0.85,
 'env_name': 'Act_Perc',
 'ep_end': 0.2,
 'ep_end_t': 10000.0,
 'ep_start': 1.0,
 'history_length': 4,
 'inChannel': 4,
 'is_sim': True,
 'is_train': True,
 'learn_start': 200.0,
 'learning_rate': 0.001,
 'learning_rate_decay': 0.96,
 'learning_rate_decay_step': 200,
 'learning_rate_minimum': 0.00025,
 'max_reward': 1.0,
 'max_step': 20000,
 'memory_size': 2500,
 'min_reward': -1.0,
 'model_dir': './dqn/model',
 'scale': 50,
 'scene_num': 24,
 'screen_height': 128,
 'screen_width': 128,
 'target_q_update_step': 50,
 'test_scene_num': 6,
 'test_step': 200,
 'train_frequency': 4}
Simulation started
Connection success!

 [*] Initialize the simulation environment
 [*] Build Deep Q-Network
 [*] Build Q-Evaluate Scope
 [*] Build Q-Target Scope
 [*] Build Weights Transform Scope
 [*] Build Optimize Scope
 [*] Build Summary Scope
 [*] Initial All Variables
 [*] Loading checkpoints...
 [*] Load SUCCESS: ./dqn/checkpoint/dqn_model_ckpt-13400
 [*] Assign Weights from Prediction to Target
 [*] Random init the scene 13 with 0 object removed
/home/ys/torch/install/bin/luajit: cannot open <../affordance_model/model.t7> in mode r  at /home/ys/torch/pkg/torch/lib/TH/THDiskFile.c:673
stack traceback:
	[C]: at 0x7fb4af384440
	[C]: in function 'DiskFile'
	/home/ys/torch/install/share/lua/5.1/torch/File.lua:405: in function 'load'
	../affordance_model/infer.lua:36: in main chunk
	[C]: in function 'dofile'
	...e/ys/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
Traceback (most recent call last):
  File "main.py", line 88, in <module>
    tf.app.run()
  File "/home/ys/anaconda3/envs/active-perception/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 72, in main
    agent.train()
  File "/home/ys/Active-Perception/DQN/dqn/agent_18.py", line 50, in train
    screen, reward, action, terminal = self.env.new_scene()
  File "/home/ys/Active-Perception/DQN/simulation/environment.py", line 483, in new_scene
    self.screen, self.local_afford_past, self.location_2d = self.camera.local_patch(self.index, (self.screen_height, self.screen_width))
  File "/home/ys/Active-Perception/DQN/simulation/environment.py", line 211, in local_patch
    raise Exception(' [!] !!!!!!!!!!!  Error occurred during creating affordance map')          
Exception:  [!] !!!!!!!!!!!  Error occurred during creating affordance map

**Comment by weiyx16** [comment]
Thank you for your interesting in our project.
I'm not sure if you have fixed this bug. But I will still provide you with the solution.
The solution is: our project based on a model called "Affordance model" from http://arc.cs.princeton.edu/, for details, you can refer to this project. The main purpose for this "Affordance model" is: given a RGBD image for current scene, it can output a heatmap over location, in which the higher value stands for higher confidence when operating on this location.
Our project is to introduce reinforcement learning into robotic grasping, i.e. let agent learn a policy to optimize the scene with certain action until we obtain a good heatmap from "Affordance model".
Here is the detail for the solution:
1. plz download the "Affordance model" from https://github.com/andyzeng/arc-robot-vision, notice we use suction-based grasping verstion of the "Affordance model" ( http://vision.princeton.edu/projects/2017/arc/downloads/suction-based-grasping-snapshot-10001.t7 )
2. Place the model ( the .t7 file ) in correct path, so the cmd in python file can execute.

If you have any questions, plz feel free to contact me. I will try my best to respond quickly!

**Comment by yangshuo11** [comment]
Thanks for your warm help! I will follow your instructions to re-run the demo.

**Comment by weiyx16** [comment]
You are welcome. Sorry, it's not a mature repo, which can't be used directly. I'll help you to debug all the stuff out.

**Comment by ChenyangRan** [comment]
> 感谢您的热烈帮助！我将按照您的指示重新运行演示。

Hi, I meet the same question as yours. And I haven't solved it.
I copy **_suction-based-grasping-snapshot-10001.t7_** into _**affordance_model and ./simulation/afford_h5.**_ .
However, it still doesn't work.
Maybe I should install Torch.
I want to ask you whether you have solved it following the links, and which folder  I should copy  _**.t7**_ into.

**Comment by yangshuo11** [comment]
> > 感谢您的热烈帮助！我将按照您的指示重新运行演示。
> 
> Hi, I meet the same question as yours. And I haven't solved it.
> I copy **_suction-based-grasping-snapshot-10001.t7_** into _**affordance_model and ./simulation/afford_h5.**_ .
> However, it still doesn't work.
> Maybe I should install Torch.
> I want to ask you whether you have solved it following the links, and which folder I should copy _**.t7**_ into.

Hi, I have loaded the model of suction-based-grasping-snapshot-10001.t7 in this way:
1. put "suction-based-grasping-snapshot-10001.t7" in the folder of "affordance_model";
2. modify the file "affordance_model/infer.lua" at line 21 like this: modelPath = '../affordance_model/suction-based-grasping-snapshot-10001.t7';

these steps can load the model successfully.

**Comment by ChenyangRan** [comment]
> > > 感谢您的热烈帮助！我将按照您的指示重新运行演示。
> > 
> > 
> > Hi, I meet the same question as yours. And I haven't solved it.
> > I copy **_suction-based-grasping-snapshot-10001.t7_** into _**affordance_model and ./simulation/afford_h5.**_ .
> > However, it still doesn't work.
> > Maybe I should install Torch.
> > I want to ask you whether you have solved it following the links, and which folder I should copy _**.t7**_ into.
> 
> Hi, I have loaded the model of suction-based-grasping-snapshot-10001.t7 in this way:
> 
> 1. put "suction-based-grasping-snapshot-10001.t7" in the folder of "affordance_model";
> 2. modify the file "affordance_model/infer.lua" at line 21 like this: modelPath = '../affordance_model/suction-based-grasping-snapshot-10001.t7';
> 
> these steps can load the model successfully.

Thank you very much, I know what caused it. I haven't find the correct path and set the arguments

**Comment by weiyx16** [comment]
> > 感谢您的热烈帮助！我将按照您的指示重新运行演示。
> 
> Hi, I meet the same question as yours. And I haven't solved it.
> I copy **_suction-based-grasping-snapshot-10001.t7_** into _**affordance_model and ./simulation/afford_h5.**_ .
> However, it still doesn't work.
> Maybe I should install Torch.
> I want to ask you whether you have solved it following the links, and which folder I should copy _**.t7**_ into.

And you also need to install Torch7, to run the .t7 model

**Comment by ChenyangRan** [comment]
> > > 感谢您的热烈帮助！我将按照您的指示重新运行演示。
> > 
> > 
> > Hi, I meet the same question as yours. And I haven't solved it.
> > I copy **_suction-based-grasping-snapshot-10001.t7_** into _**affordance_model and ./simulation/afford_h5.**_ .
> > However, it still doesn't work.
> > Maybe I should install Torch.
> > I want to ask you whether you have solved it following the links, and which folder I should copy _**.t7**_ into.
> 
> And you also need to install Torch7, to run the .t7 model

Yeah, now I'm struggling to install Torch7 and then test it.

**Comment by weiyx16** [comment]
> > > > 感谢您的热烈帮助！我将按照您的指示重新运行演示。
> > > 
> > > 
> > > Hi, I meet the same question as yours. And I haven't solved it.
> > > I copy **_suction-based-grasping-snapshot-10001.t7_** into _**affordance_model and ./simulation/afford_h5.**_ .
> > > However, it still doesn't work.
> > > Maybe I should install Torch.
> > > I want to ask you whether you have solved it following the links, and which folder I should copy _**.t7**_ into.
> > 
> > 
> > And you also need to install Torch7, to run the .t7 model
> 
> Yeah, now I'm struggling to install Torch7 and then test it.

In the beginning, I paid a lot to convert the torch model to pytorch model, which will speed up the training process and save the trouble caused by torch. But I failed, for a certain structure in this model can't be transformed...

**Comment by ChenyangRan** [comment]
Ｈi, I have installed Torch7 and Lua5.1, and the *.t7 is in the correct folder.
Then I type
> python main.py --is_train=True or python main.py --is_train=False --is_sim=True  

There are still some errors.
![1](https://user-images.githubusercontent.com/29306735/66737787-7912d980-ee9f-11e9-90f7-85e1cbaabe2c.png)
It seems that my GPU is not enough to test codes.
However, it still exits when I set the batch_size=4 in ./DQN/config.py.
And I have write **_os.environ['CUDA_VISIBLE_DEVICES']='0'_** in main.py, it doesn't solve problem.
Have you met this one?
Here is the config about my GPU:
![2](https://user-images.githubusercontent.com/29306735/66738003-05250100-eea0-11e9-9d7f-d7432f5a40e5.png)

How much GPU memory does your program need?

**Comment by weiyx16** [comment]
PLZ try to change the gpu fraction param [here](https://github.com/weiyx16/Active-Perception/blob/master/DQN/main.py#L30). This param is to assign how much gpu memory to DQN part, maybe you can set it with a smaller number to leave more space for *Affordance Map*, which will take about 2.5G memory, as far as I remembered.

**Comment by ChenyangRan** [comment]
> PLZ try to change the gpu fraction param [here](https://github.com/weiyx16/Active-Perception/blob/master/DQN/main.py#L30). This param is to assign how much gpu memory to DQN part, maybe you can set it with a smaller number to leave more space for _Affordance Map_, which will take about 2.5G memory, as far as I remembered.

I set 
>flags.DEFINE_string('gpu_fraction', '50/100', 'idx / # of gpu fraction e.g. 1/3, 2/3, 3/3')

Now it works well.
I don't know how to thank you. Thank you for your help in my testing.

**Comment by weiyx16** [comment]
You are welcome. It's not a mature repo, without detailed documents, which may cause you much more time to use it. Hope you can get motivated by this project and explore something more.
