### ISSUE TITLE
No module named 'dqn'

### ISSUE THREAD

**Issue by ChenyangRan** [weiyx16/Active-Perception#4]
Hi, I use the cmd:

> python main.py --is_train=True

It shows that **_No module named 'dqn'_**. But I find there is dqn folder.
Maybe the error is from  

> from dqn.agent import Agent

Could you please help me?

**Comment by weiyx16** [comment]
Have you git clone the whole repo? I'm not sure, for I'm also confused by module input with python.
Maybe you can try to change the file *agent_8.py* or *agent_18.py* in **dqn** folder to *agent.py*, the main difference between these two files is a little modification on U-Net structure.

**Comment by ChenyangRan** [comment]
> Have you git clone the whole repo? I'm not sure, for I'm also confused by module input with python.
> Maybe you can try to change the file _agent_8.py_ or _agent_18.py_ in **dqn** folder to _agent.py_, the main difference between these two files is a little modification on U-Net structure.

Thanks for your reply.
Now I have install all the requirements and test your pkg.
However, when I type

> python main.py --is_train=False --is_sim=True  

![1](https://user-images.githubusercontent.com/29306735/66577070-5173f680-ebab-11e9-893a-96c150c96d49.png)

I think maybe I don't use v-rep. Then I use **_./vrep.sh_** and **_start simulation_.**
Then type **_python main.py --is_train=False --is_sim=True_** , it also don't work.
![2](https://user-images.githubusercontent.com/29306735/66577330-c5160380-ebab-11e9-96d4-f31ae6772236.png)

It seems that I should use the real hardware. But I just want to test DQN in simulation.
Could you please help me? I'm sorry that I don't know how to use v-rep well.
By the way, Torch 7 is needed if I just want to test DQN?

**Comment by ChenyangRan** [comment]
And should I write **_simExtRemoteApiStart(19999)_**  in kinect and UR5 under ./simulation/Simulation.ttt?
Such as :
![3](https://user-images.githubusercontent.com/29306735/66580320-cbf34500-ebb0-11e9-8705-6d6163c0770c.png)

Looking forward to your reply.

**Comment by weiyx16** [comment]
### Use V-Rep
I use V-Rep as follows:
+ Type in *./vrep.sh* and the software will launch.  
+ Open scene file. In our repo, we use *./simulation/Simulation.ttt*.  
+ To start connection between python script and V-Rep (kind of network connection, use port & C/S structure), you should type in *simRemoteApi.start(19999)* in the bottom command line of V-Rep. Use a screenshot from website:
![Snipaste_2019-10-11_10-23-15](https://user-images.githubusercontent.com/29686453/66619921-3dfb7680-ec11-11e9-9522-3ba5d3e1eaba.png)
+ Start the V-Rep simulation, then you can use python script.

I'm not very familiar with V-Rep, for I only need it to a simple scene simulation. Maybe you need more skills, you can directly search in the website :-)

### About the running
There's another mistake I notice that, the environment you run is actually this one: ***./experiment/environment.py***, but it should be running this one ***./simulation/environment.py***. I'm not sure why this error occured. Maybe you print if the params *is_sim* really set to be *True* at here at **Line 72** in main.py:
```python
        else:
            print(config.is_sim)   # New
            if config.is_sim:
                env = DQNEnvironment(config)
                agent = Agent(config, env, sess)
                agent.play()
                agent.randomplay()
```
If it is *False*, you can try to set it to be True directly here, else I will check where the bug is. Thank you.
### Dependency
Torch7 is needed by ***affordance model*** , the DQN itself only depends on ***tensorflow***

**Comment by syx0629** [comment]
我把这个注释掉
```shell
from experiment.environment import REALEnvironment
```
即可运行，但是又有以下报错
```
 [*] Initial All Variables
W1011 12:40:03.128700 140191881737984 deprecation_wrapper.py:119] From /home/user/paper/Active-Perception/DQN/dqn/agent.py:495: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

 [*] Loading checkpoints...
W1011 12:40:03.146040 140191881737984 deprecation.py:323] From /home/user/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
I1011 12:40:03.146778 140191881737984 saver.py:1280] Restoring parameters from ./dqn/checkpoint/dqn_model_ckpt-13400
2019-10-11 12:40:03.370971: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key prediction/7_lq_1/biases not found in checkpoint
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/user/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/user/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: Key prediction/7_lq_1/biases not found in checkpoint
	 [[{{node save/RestoreV2}}]]
	 [[save/RestoreV2/_19]]
  (1) Not found: Key prediction/7_lq_1/biases not found in checkpoint
	 [[{{node save/RestoreV2}}]]
0 successful operations.
0 derived errors ignored.
```

**Comment by ChenyangRan** [comment]
> ### Use V-Rep
> I use V-Rep as follows:
> 
> * Type in _./vrep.sh_ and the software will launch.
> * Open scene file. In our repo, we use _./simulation/Simulation.ttt_.
> * To start connection between python script and V-Rep (kind of network connection, use port & C/S structure), you should type in _simRemoteApi.start(19999)_ in the bottom command line of V-Rep. Use a screenshot from website:
>   ![Snipaste_2019-10-11_10-23-15](https://user-images.githubusercontent.com/29686453/66619921-3dfb7680-ec11-11e9-9522-3ba5d3e1eaba.png)
> * Start the V-Rep simulation, then you can use python script.
> 
> I'm not very familiar with V-Rep, for I only need it to a simple scene simulation. Maybe you need more skills, you can directly search in the website :-)
> 
> ### About the running
> There's another mistake I notice that, the environment you run is actually this one: _**./experiment/environment.py**_, but it should be running this one _**./simulation/environment.py**_. I'm not sure why this error occured. Maybe you print if the params _is_sim_ really set to be _True_ at here at **Line 72** in main.py:
> 
> ```python
>         else:
>             print(config.is_sim)   # New
>             if config.is_sim:
>                 env = DQNEnvironment(config)
>                 agent = Agent(config, env, sess)
>                 agent.play()
>                 agent.randomplay()
> ```
> 
> If it is _False_, you can try to set it to be True directly here, else I will check where the bug is. Thank you.
> 
> ### Dependency
> Torch7 is needed by _**affordance model**_ , the DQN itself only depends on _**tensorflow**_

Oh, thank you very much. 
I think I have fixed it.
> 
> ```python
>   from simulation.environment import DQNEnvironment
>  #from experiment.environment import REALEnvironment   # New
> ``` 

Ｍaybe it happens here:

> ```python
> """
>     Set Kinect:
> """
> logger = createConsoleLogger(LoggerLevel.Debug)
> setGlobalLogger(logger)
> 
> fn = Freenect2()
> num_devices = fn.enumerateDevices()
> if num_devices == 0:
>     print(" [!] No kinect device connected!")
>     sys.exit(1)
> ```

It seems that the code will run and warns me when I import _**./experiment/environment.py**_ .

Now I have problems on load map, and have post my question on **Error occurred during creating affordance map #3**  issues.
Looking forward to your reply.

**Comment by weiyx16** [comment]
Glad to hear that. I have noticed the problem you mentioned in issue #3 . I will figure out what's wrong.

**Comment by weiyx16** [comment]
Glad to hear that. I have noticed the problem you mentioned in issue #3 . I will figure out what's wrong.
