### ISSUE TITLE
No module named tensorflow

### ISSUE THREAD

**Issue by vRicardo98** [weiyx16/Active-Perception#7]
Greatings!

I am trying to run your code for a university project, however i am facing the fact that it says "No module named tensorflow" even tough i have it installed as you can see in the prints below. What can I do to solve this problem?

![tensorflow](https://user-images.githubusercontent.com/41165271/104018803-5a8ab380-51b2-11eb-87b2-4fc876f2543d.png)
![tensorflow-error](https://user-images.githubusercontent.com/41165271/104018812-5ced0d80-51b2-11eb-80ba-232fb98007fa.png)

**Comment by weiyx16** [comment]
Have you tested with ```python``` in command line and try to ```import tensorflow as tf```?

**Comment by vRicardo98** [comment]
Well, gotta say I just tried in with Python3 (3.6.9) and it doesn't recognize it.
I then installed Python2 (2.7.17) and the respective Pip. Proceed to install tensorflow and tensorflow gpu (1.4.0) and It did recognize. Gotta try run your code with python2 then.

Many thanks!!

**Comment by weiyx16** [comment]
You are welcome. The total code was only tested on python3. So, I think you need to solve the problem of using tensorflow under python3, which actually has no dependency on what the repo is. You can search on google to find some solution.
