### ISSUE TITLE
ImportError: libpcl_visualization.so.1.8: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Marwanon** [weiyx16/Active-Perception#8]
Hi Dear

I tried to run the code but I got this sort of error 
`ImportError: libpcl_visualization.so.1.8: cannot open shared object file: No such file or directory`

I have tried to install the pcl module but I face the same problem!!!
may I got a help to settle this issue 

I would appreciate your help

**Comment by weiyx16** [comment]
I think the best solution for problems related to environment or libraries is to search in google or other forums. Really hope to help you, but this kind of problem is really dependent to each situation.. If you paste the full error msg, maybe I can find something.

**Comment by Marwanon** [comment]
Thanks for your reply 

Here is the the massage 

`(marwan2) marwan@marwan:~/Downloads/zib file/Active-Perception-release/DQN$ python main.py --is_train=True
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from dqn.agent_8 import Agent
  File "/home/marwan/Downloads/zib file/Active-Perception-release/DQN/dqn/agent_8.py", line 16, in <module>
    from .replay_memory import ReplayMemory
  File "/home/marwan/Downloads/zib file/Active-Perception-release/DQN/dqn/replay_memory.py", line 8, in <module>
    from util.utils import *
  File "/home/marwan/Downloads/zib file/Active-Perception-release/DQN/util/utils.py", line 6, in <module>
    import pcl
  File "/home/marwan/anaconda2/envs/marwan2/lib/python3.6/site-packages/pcl/__init__.py", line 2, in <module>
    from ._pcl import *
ImportError: libpcl_visualization.so.1.8: cannot open shared object file: No such file or directory
`

I appreciate your help

**Comment by weiyx16** [comment]
It seems that the ```pcl``` module is broken in your environment: (you lost the link or the file of ```libpcl_visualization.so.1.8```). You can paste this(```from ._pcl import * ImportError: libpcl_visualization.so.1.8: cannot open shared object file: No such file or directory```) and search in google. Here is what I found: https://github.com/strawlab/python-pcl/issues/158, and you can try it.
